//
// Created by samuele on 15/05/19.
//

#ifndef TSP_OPTIMIZATION_GUROBI_PEACEFUL_QUEENS_OPTIMIZATION_H
#define TSP_OPTIMIZATION_GUROBI_PEACEFUL_QUEENS_OPTIMIZATION_H

void tsp_queens_model_create();

#endif //TSP_OPTIMIZATION_GUROBI_PEACEFUL_QUEENS_OPTIMIZATION_H
